name: Evaluatory Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "0 * * * *"
jobs:
  test:
    timeout-minutes: 290
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Evaluatory
      run: time yarn run evaluatory --config pcnacom.config.json
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: evaluatory-results
        path: evaluatory-results/
        retention-days: 90
